---
title: "About"
date: 2018-09-19T19:02:09-04:00
draft: false
---


* Who's this Z guy?

Hi, I'm Mike Zamansky. 

I'm a professsor at Hunter College working on two major projects. One
is to create and run a program to certify middle and high school
computer science teachers. 

We're also creating a new CS undergraduate honors program and I'm the
mentor. We're going to be one of the few CS programs that in addition
to giving our students all the CS background and theory, will connect
students to current industry practices and opportunities. I'll be
relying heavily on the alumni network - the StuyCS family that I've
worked to create over the past quarter century.

Prior to moving to Hunter, I spent almost 25 years at Stuyvesant High
School. I created and built its CS program and have had the pleasure
and privilege of working with many amazing students and teachers.
 
I also love tabletop gaming, cooking, baking, biking and a variety of other things.

Hope you enjoy my ramblings.

If you want to connect, you can always email me at [[mailto:zamansky@gmail.com][zamansky@gmail.com]].



