---
title: Cohort 3 End Of Summer
date: 2022-08-03T11:45:33-04:00
tags:
- misc
categories:
- misc
draft: true
--- 

Yesterday was the last day of classes for our current cohort. The
rest of the week and maybe weekend will be all grading all the time
and then I'll try to tune out work for a couple of weeks to try to
recharge the batteries. Since there are some ongoing Hunter
administrative snafus I'm not all that optimistic on getting real down
time.

So, how did it go?

Overall I'm happy with the results. We had a much larger cohort -
almost three times the size of past years so that presented challenges
but at the end of the day the participants showed a lot of growth and
based on our anonymous survey the vast majority were very happy with
the experience. There were a couple who were not happy with the
experience (or more likely, us instructors) but in a large group,
particularly of teachers being taught, you're not going to please
everybody.




* Challenges

The large group was a challenge but I'm not really sweating it since I
don't expect there to be cohorts nearly this large in the future. I
had a personal goal of getting NYC to around 100 teachers ASAP and
that'll be done once this cohort finishes in the spring but I suspect
that as we move on, there will be less demand for teachers getting an
additional CS certificate while on the other hand, there will be a
slow and steady increase in demand for Masters programs. At the same
time, additional programs should start coming online across the state.

The end result should be no more classes of 60.

We also had elementary school teachers for the first time. This added
an additional axis of complexity. We couldn't do a whole lot about
some of it. The state created a K12 cert so there's no way around it,
all students must learn the CS we feel is needed for a 12th
grader. Creating two tracks isn't an option even though it would make
more sense.

The other challenge was the spread of expertise. Other than saying
that most of the participants were real troopers on both sides of the
experience spectrum I'll leave this alone since it's not appropriate
for a public post. 

* Good Stuff

As I just said, most participants were real troopers. Most of the
participants with strong CS backgrounds put on their teacher hats and
helped support less experienced teachers. We'd frequently drop in and
lurk in a breakout room to see the more expereinced guide the room and
it was rare to see one of them dominate and just "do the task"
(although it did occasionally happen).

Also, based on the comments the cohort is building a strong sense of
community. There were a couple of comments where a student or two felt
otherwise, but they were in an extreme minority (based on the
anonymous surveys) and from their full comments it looks like they
just didn't buy into the program at all.

We also had a handful of participants from outside the city with five
from up near Ithaca. It was great adding them to the mix and I think
there will be some rich discussions in the Fall in curriculum
development when we can not only contrast schools but entire
districts.

Of course, at a base level, there's also the fact that everyone got
through the program and there was a lot of growth across the board. 

For me personaly, the highlight was getting to know a bunch of great teachers
and people and to be able to work with my team again. My team from
Stuy is still the thing I miss most at Hunter. It's funny, we had one
of my CS colleagues from Hunter also on the team and he commented on
how great it was to work with this team and how well we worked
together. A number of students also pointed that out as a positive
(well, not the couple of negative nellies mentioned prior but again,
the majority of the cohort).



* A couple of things that stood out

These are just a few things that have been on my mind since
closing. Maybe their important, maybe not and I might change my own
mind down the line. Still, these are few random or tangental things
that stood out from the past month.

** The state of CS PD

This year, when I saw the spread of CS expertise, I decided to dig
deeper into teacher backgrounds. I also looked back to the teachers
from the first two cohorts who came in barely able to write "Hello
World!"

In many, indeed most of these cases the teacher had gone to the
standard PD sessions - mosty through CS4All in NYC but sometimes from
the usual suspects of providers independantly through their school.

I then looked to see how long these teachers were doing these PDs.

In many cases ot was years - three, four, five, or even more years of
going to CS training.

This really alarmed me. Well, actually, I suspected this but it was a
sobering confirmation. I know a lot of people won't want to hear this
but teachers attending CS "training" for multiple years should be well
beyond the most basic of programs. Even if they haven't used a text
based language, after multiple years, they should be able to
transition fairly easily.

So, I know that a lot of people might be offended by my saying this
but I stand by it. There are some providers I know who do good work
but I think what I saw here is an indictment of the overall PD
approach that, to paraphrase what code.org said a few years ago,
"trained XXXXX CS teachers" in a very short period of time.

** Split the class

Another interesting thing is that there weren't a lot of comments from
particpants about the mixed teacher levels in terms of sharing
experiences. On the other hand many would have loved us to be able to
split based on programming experience. I haven't had a chance to do a
deep debrief with JonAlf and Topher who ran the methods components but
this was a little bit of a surprise. We'll see if this becomes a
larger discussion topic in Curriculum Development.

On the splitting for programming level we couldn't do that for
assorted reasons and moving forward I expect it not to be an issue.


** Teaching Methods and Best Practices

We approach methods, and in fact our approach to teaching in general
is all about helping teachers build a toolbox. We have to do a better
job at communicating why this is our approach.

There were a couple of comments both in class and in the survey about
"best practices" and "the research" with respect to methods. I get it,
younger teachers are hit over the head with this type of edubabble
from there first education course through every department meeting,
PD, and observation.

The trouble is that there are no "best practices," there are practices
that under certain circumstances, based on a combination of students,
teacher, school, culture and more can be most effective for **THAT
SPECIFIC TEACHER** to use in that time at that place. Teachers aren't
usually taught this, they get hammered with "best practice" and "the
research" but nobody ever tells them that while there are some people
doing great work in Ed research and CS Ed research, the field is
generally held in low regard, work is almost never replicated and when
you read most of it, there are tons of important variables that
the research leaves out.

On top of this, we can go down a long list of "best practices" which
were foisted upon teachers as the one true way only to be replaced a
few years later with the new "best practice."

We believe in building a toolbox of content and techniques and we
trust teachers to know their own strengths and weaknesses as well as
their student needs and that they'll use the right tool at the right
time.

** Writing plans from scratch 

Another thing I noticed was that when we got to the lesson planning
unit, a lot of teachers really wanted to base their work off of a
canned lesson. They said they wanted to adapt it but they were really
reluctant to come up with something on their own, only using other
resources for examples, references, etc.

I was a little surprised about this reluctance but upon thinking, it
makes sense. Even if they adapt lessons, CS PD and training is all
about providing canned lessons to teachers so in many cases, it's what
they're used to. Add to that the fact that this was for an Education
class, and to be honest, the demands and rigor of education classes
vary greatly  and in many cases the default approach is path of least
resistance. I get it. I did many an Ed class where I threw together a
quick paper from prefabbed sources to get my A for the semester. I'd
like to think, though that our program is a bit better than that.

I think the cohort ended up doing it right and with the right attitude
but I think it's interesting to see what teachers are normally
presented with and how that contrasts, good or bad, with what my team
is selling.

* What's next

So, summer's in the books. We'll take this group through a few more
courses in the Spring they'll join the ranks of New York State
Certified CS Teachers. 

Personally, I'm going to try to disengage from Hunter related stuff
for the next few weeks and try to recharge. there will be a few things
I have to deal with. After a few really hard years I'm hoping I'll
start up again at the end of the month with some renewed energy.

I also have to give some thoughts to the long term both for Hunter and
me. Devorah turned 55 last November and I join her in October so as
many of you know, we've got some potential big things to
consider. More on that though once the year starts.

