---
title: School leadership and COVID, or not
date: 2020-09-16T09:48:51-04:00
tags: 
- policy
categories: 
- policy
draft: false
--- 

Teachers are back and students will soon follow either in person or
remote. In person means in person one or two days a week with the
rest of the time from home.

This of course shows horrible leadership. It fails in terms of
education, safety and even freeing up parents to get back to
work. After all, if your kid is only in school one or two days a week
it hardly allows you to get back to your own full time job. 

Of course the plan gets worse. It's optimized to provide the worst
possible educational experience. I won't rehash the plans here but
it's looking to increase the teachers workload tremendously while at
the same time killing continuity for the students (unless of course
the DOE can hire thousands of extra teachers and somehow arrange for
them to mind meld with the  main teacher). I'm not going to hash out
the details here but they're easy enough to find on the interwebs.

Now in terms of leadership I'm not writing about De Blasio or
Carranza. We all know they're absolutely horrible. It's hard to
believe Carranza was actually a classroom teacher at one point and
while I'm no fan of Bloomberg on education at least you could say that
he had a vision, albeit an incorrect one of applying business sense to
schools and followed it while De Blasio is tone deaf, arrogant and
clueless which could make him more dangerous. I'm talking about in
school leadership.

What did schools do? Well some tried to make the best of a bad
situation. They recognized that the Mayor's hybrid model was bunk and
while safe full time in person is clearly the best choice, fully
remote, even with its difficulties and limitations  would be more
sound than hybrid. Add to that the fact that if a school had to go
remote midstream you'd be set even further back [fn:1]. These schools
decided to basically set up remote from in school. Students who wanted
to or had to go to school would be sent to specific parts of the
school where they would receive the same remote instruction as their
classmates. This would accommodate students who couldn't work from
home while allowing for a sensible overall schedule.

Sounds like good leadership to me and in some cases it is. On the
other hand, in some cases you have to  dig deeper.

The first question has to do with the student pods. Can they be set up
safely. What about entering and leaving? Bathrooms? Lunch? I'm
guessing some schools have a good plan in place but I've also heard
teachers refer to their upcoming student learning pods as "deathpods."

The next question has to do with teachers working from the building or
from home. The DOE decreed that unless you get a medical excemption
you *have* to work from school. Who cares if you're meeting students
in person or not, you *have* to be there. This was ridiculous. I've
already written about it - [[https://cestlaz.github.io/post/scared-teachers-scared-students/][scared teachers can't teach]]. This is where
leadership kicks in. I've heard through the grapevine that some
schools had teachers working from home without DOE permission. Sounds
like good leadership to me - trust your people to do the job and do
the right thing.

Recently, the DOE backpedaled and gave schools the ability to allow
teachers to work from home without medical excemptions so long as it
worked within their COVID plans. Looks like some schools are jumping
on this.

Unfortunately, others aren't. I've heard of principals that are
setting up their schools to be "remote from school" but requiring all
teachers show up in person even though they clearly don't need all of
them on site. This is the type of "leadership" I've come to expect
from many of the Bloomberg era principals I've met - you know, the
ones that barely taught for a cup of coffee. Insisting that teachers
brave the subways and share facilities like bathrooms only to spend
the day teaching in isolation serves no purpose other than to exert
power over them. If a teacher is teaching all remote and isn't needed
for the pods, let them teach from home. They'll be more comfortable
and thus more effective. 

It sounds like some principals are being true educators and leaders in
these times but many are not and in these times when we can't count on
our elected officials or his appointees to do the right thing, we need
all our principals to step up.

* Footnotes

[fn:1] Note that I'm only talking here about the general population at
the high school level. I don't claim to know the best format for the
younger grades and accomodating special needs students are a whole
different kettle of fish.
