---
title: Election Thoughts - feeling hope but still concerned
date: 2020-11-08T06:56:55-04:00
tags: 
- misc
categories: 
- misc
draft: false
--- 

I don't usually talk  politics on this blog but it is the news of the
day. We truly are at a turning point in this country and we should all
be concerned with the road we take.

Yesterday the media outlets called the election for Biden/Harris. It's
not over but I thought this would be as good a time as any to share
some thoughts and more importantly concerns.

Let's look at some of the bad that we've got to pay attention to

* The Bad
- 70,000,000  voted for Trump.

  That should be both sobering and
  frightening. Some of these are rich selfish people, some are racist,
  some brainwashed by Fox and AM talk radio but there's also a huge
  undercurrent of lack of decency.  

  Trump has time and again shown these traits: bullying, ignorance,
  protectionism, isolationism, ignorance, compulsive lying, misogyny,
  divisiveness, racism and white supremacy.

  A vote for Trump says that none of those were disqualifiers. A Trump
  voter may fancy themselves not racist but are fine with a racist as
  the American President.

  This should be very concerning. 
 
  Can we educate this group? Bring them over? We should not and can
  not just all be friends and pretend nothing ever happened. If I've
  got a friend who has any of the above traits I hope that I'd try to
  bring them over from the dark side but our friendship would be over
  if they just doubled down as Trump and Trump supporters have done
  time and agian.
  
- Republicans leaders haven't congratulated Biden/Harris

  Republican leadership has shown no indication of recognizing or
  wanting to work with our new Presiden. How will the Democrats react?
  Will they "reach across the aisle" only to be burned again? This
  would be a HUGE mistake. Sure, now is the time to extend the olive
  branch but come January, if the republicans still want to go
  scorched earth the Democrats must respond. 

- It ain't over til it's over

  Trumps team *and* the GOP are still forging ahead to contest the
  election and some GOP leaders are telling states to forgo the will
  of the people and quite simply give the election to Trump. Even if
  this doesn't happen this should terrify you. Even if all goes well
  and we move on to a Biden/Harris presidency, these GOP leaders are
  still in power and they've shown their true selves.


- The Democrats still refuse to learn
  
  I thought Biden's speech was great last night. He hit all the right
  notes but let's see what the party actually does.

  Right after the election I saw tweets from Democratic candidates
  attacking the progressive wing of the party yet to my knowledge all
  the candidates that actively campaigned on progressive issues
  won. It wast he old school Democrats (that is, the ones who are
  really 1980s republicans with better social positions) that had
  difficulties. It certainly appears that most Americans want police
  reform, health care that's not contingent on employment or being
  independently wealthy and I do dare say most don't want to destroy
  the planet. 

  If the Democrats continue to ignore the future, ignore the working
  and middle class, address income inequity and the aforementioned
  progressive line items we'll be back where we were in 2016 before
  you know it.

- Low turnout

  Finally, on the bad side, even though the past few presidential
  elections have had record highs for voter turnout we're still under
  50% which is just sad. We have to both address the GOP's repeated
  attempts to disenfranchise voters and get more people to the polls.

* The eh

Senate is still up in the air but it doesn't look like the Republicans
will lose control. It's bad but I can't say it's a failure. It's
certainly bad that Kentucky keeps sending McConnell to the Senate with
him possibly doing more damage than even trump but not a surprise. The
Democrats shouldn't have lost seats in the house  but I haven't dug
into those races carefully enough to say anything.


* The Good

Fortunately, there's some good as well.

- close to 75,000 voted for Biden/Harris

  That's millions more than voted for Trump and they got support from
  all corners. This is terrific. Biden wasn't my first choice nor was
  Harris but both have grown on me and it looks like a broad coalition 

- Blue wave?

  While it may not seem like there was a blue wave, maybe there
  was. Taking the senate was probably not a realistic goal and there's
  still a chance. You could say the Democrats lost some seats but
  instead of comparing 2020 to the midterms, compare 2020 to 2016 when
  the Republicans held the house. This plus looking at the states that
  went or still could go Biden? Maybe there was a blue wave afterall.

- The world response

  Certainly seems like our allies are happy with the results.

- We have a first dog

  Nuff said.

- The response of the American people.

  Parties in the streets all across the country. In New York, the
  party started with the announcement and kept going through the
  evening. 

  I've *never* seen anything like this before. Not even when Obama was
  elected. I saw tweets talking about how this is the behavior you see
  when dictators are overthrown. Well, there you have it.

  This outpouring of emotion and relief never seen in our lifetime in
  America This says a lot about where we are and where we were.


* What's next?

That's the question. 

If the parties don't change nothing's going to change and the parties
aren't going to change unless the people force them to change. Groups
like [[https://brandnewcongress.org/][Brand New Congress]] are a start but we've all got to be active
supporting candidates (or running), calling out injustice, using our
position and platforms for those that can't.

It's been a rough four years and a super stressful election
season. 

I'm still concerned about this election and very concerned
about our future but for the first time in a while I'm also hopeful. 

Just remember though, hope without action won't take us from hope to
reality.

