---
title: Yes, deadlines do matter
date: 2022-05-17T08:28:56-04:00
tags:
- teaching
- pedagogy
categories:
- teaching 
draft: false
---

I've been seeing a few threads lately talking about the virtues of
allowing students to hand in assignments late. Not just late but
pretty much whenever they want. This attitude seems to be related with
things like mastery or specification grading, which I believe in but
it's not the same thing.

The threads start with someone saying that assignments shouldn't have
deadlines or some variant and the thread proceeds with a bunch of
people chiming in as to why a teacher who actually enforces deadlines
is an inhuman monster.

Nonsense.

Now, before I dive in, I do think that a teacher should have some
flexibility with deadlines but allowing students to hand in anything
at any time is probably not a good idea in most cases and any teacher
or self styled educator who proudly proclaims that deadlines in all
cases are evil should just step off their soap box and maybe look more
into their own teaching practice. Of course, the teacher that likewise
says strict to the minute deadlines with no flexibility should do the same.

Let's look at both sides.

* Advantages of no deadlines

The push here is that students have things going on outside of school
and an arbitrary deadline doesn't account for this. Particularly over
the past couple of years students have had to contend with all sorts
of difficulties that could be unique or semi-unique to them or at
least they hit at different times.

The other push is that students might get certain concepts at
different times so a student might not be able to finish something
when originally assigned but could very well have mastered the concept
by the end of the term.

Finally, there's the thought that those most susceptible to missing
deadlines are the most in need of support. 

I agree with these issues and do feel that some deadline flexibility
is warranted or at least some mechanism to mitigate a missed deadline
or two or a bad grade and I certainly agree with the idea that the
important thing is that the student gets it at the end and not
necessarily that they get it when first introduced.

That said, the idea of largely or wholly eliminating deadlines just
doesn't fly.

* Why deadlines matter

The usual first response is that having no deadlines rewards bad
behavior. This can be true but it really depends on circumstances. On
the other hand there are some legit reasons for deadlines.

A big one is snowballing - some courses are compartmentalized. The CS
topics course I just taught was. Each unit was independent so in
theory any could be completed at any time. Here the snowballing is
just the overall amount of work. If completing one assignment say,
every two weeks is a challenge for a particular student, imagine when
they let the deadlines slip and then have to complete 6 at once.

It's worse though in courses that do build. I taught data structures
last semester. You can't build your linked lists without understanding
your pointers and you can't build an open hash table without those
linked lists. If you can't do the pointers you're going to really be
at a loss for those other topics. This means making sure a student
*can* successfully master what's needed by the dealine *is* important
and not arbitarary.

Another reason is that, in spite of the no-deadline crowds
contentions, deadlines *do matter* in the real world. You're not
getting on that plane once the door at the gate closes. Likewise, I'm
sure you'd be pretty unhappy if your house burned down because the
fire department had to finish their dinner before heading over to put
out the blaze. Also, try getting into college if you miss the
application deadline. 

Usually, deadlines are more flexible and the penalties for missing
them are less severe but they do indeed exist. If you miss a client
deadline you might lose the client, if you don't pay your bills,
eventually the collectors will come for you. 

Even without the penalties there's also a matter of respect - not just
for the teacher but also for your classmates. Putting aside the legit
reasons for missing deadlines, some students will indeed either be
lazy on not focused or might just be taking advantage of a more
lenient teacher. This student is then given more attention from the
teacher - since teacher time is limited, that's going to be at the
expense of the other students - not fair and not cool. If the reason
for missing a deadline is legit, then no problem but as we all know
there are plenty of people who'll take advantage of any system that
lets them.

Another big reason for deadlines that's never talked about is that
many students want and/or need them. Over my 30+ years as a teacher,
I've tried strict deadlines, no deadlines and everything in between. I
can't tell you how many students have told me that they needed
deadlines to keep them on task and in fact, deadlines with internal
targets to meet helped even more. 

Finally, one has to consider the teachers workload and schedule. It's
time to drop the "hero teacher" bit. Teachers *should* have a work
life balance and that means not being available to handle student
issues 24/7. I hate grading and it takes me a lot of time and
effort. When I grade, I set up my systems to be efficient and I get
into a grading groove. If a student hands in something late, even with
a good reason, it breaks my flow and takes me much longer and also
ties me up in other ways. Sure, if I taught at an "elite" private
school and only had a dozen kids in a class I could make all sorts of
accommodations but when you teach 5 of 34 every day somethings got to
give. The teacher also has their own deadlines - students must know
this or that before the AP or standardized test and of course the big
deadline - getting those grades in.


* What do I do?

So, where do I ultimately fall on this? I do believe in deadlines but
I believe in some flexibility. I also like to have enough information
on my students so that by the end of the term I can assess them even
if one or two things are missing.

Are my deadlines hard? Not really - anyone can ask for an extension
but my two requirements are:

1. They have to have shown that up to the request they've tried to
   make some headway on the project. This is easy since I use Git and
   GitHub so I can just log at their logs.
2. They speak to me about the extension before the deadline and by
   this I mean as soon as there might be an issue, not the evening
   before the project is due. I encourage them to speak to me even if
   they think there might be an issue to get my okay and then, more
   often than not, they don't use the extension.

Some teachers don't like the fact that I require that the student
actually talk to me about an extension and that they do it in what I
consider a timely manner but I think at some point the students must
advocate for themselves.

So, how does it work for my classes? I think pretty well. I'll take
almost any reason - sickness, family event, lots of other things due,
something's unclear or almost anything else. We discuss it and come up
with a fair extension. I usually ask "what do you need" in terms of
time, resources, and in some cases help and then I try to give that
plus a cushion.

So, what do you think? Are you part of the no deadline crowd? What am
I missing? Got other strategies and techniques? Let's hear them as
well.


