---
title: Retiring part 3 - What's Next
date: 2022-11-09T19:40:01-04:00
tags:
- misc
categories:
- misc
draft: false
--- 


* Links to the three posts in this series:
If you're seeing this before the previous two posts, I'd encourage you
to read post 1 and 2 first.

 - Post 1: [[/post/retiring-1-why/][Why I'm retiring]]
 - Post 2: [[/post/retiring-2-accomplishments/][What was accomplished at Hunter]]
 - Post 3: [[/post/retiring-3-whats-next/][This post]]   


As I said at the start of these three posts, I do want to stay in the
game. Maybe take a break and definately slow down but I still think
I've got something to contribute.

I'm writing this so that you can have it in the back of your mind in
case a great match appears either soon or somewhere down the road.

I think I posses a somewhat unique set of skills and experiences. A
thirty year teacher with a strong CS/Tech background, I've taken students
from blank slate to industry, created entire programs, and worked with
educators from early grades through college level.

I've also worked as a software engineer and have remained in touch and
connected with the tech industry.

What might be appealing?

Not sure.

Probably not full time and since I'll be collecting my pension it'll
be about fit much more than money. Still, I'd never say never on the
right opportunity.

I'd love the opportunity to travel more - even if just in the
region. I think that's my biggest regret is that Devorah and I really
never had the opportunity or took the time to see the country or
world.

Maybe if a company wants someone as a rep at conferences like all
those Ed Conference sponsors or who knows what else.

I'd also be open to longer gigs elsewhere - a month, a semester, or
even a year on an interesting project where we can get to know a new
community.

I know the big tech companies work with colleges to try to help them
do what I did with Daedalus at Hunter. Given that none of them have
people with the range of educational experiences and successes I
have, they could do far worse than engaging me to help with these
programs.

Maybe some colleges, universities, or governments have a side project
and they could use someone like me.

To be honest, I don't know but figured this was a good way to get the
word out.

So, thanks for reading and keeping me in mind.

Now, back to our regular blogging program.

* Links to the three posts in this series:
 - Post 1: [[/post/retiring-1-why/][Why I'm retiring]]
 - Post 2: [[/post/retiring-2-accomplishments/][What was accomplished at Hunter]]
 - Post 3: [[/post/retiring-3-whats-next/][This post]]   
