---
title: Teachers and Police
date: 2020-06-07T10:56:52-04:00
tags: 
- misc
categories: 
- misc
draft: false
--- 
* Teachers and Police 

It's been an ugly few days but perhaps in some ways a hopeful few as
people have been making their voices heard like never before in my
lifetime. We've seen and endless stream of videos of peaceful protest
and far too many instances of police officers overstepping their
bounds. I keep hearing about violent protesters but those videos seem
to be avoiding my feeds as are the videos of law enforcement going
after the looters who are a separate group from the protestors.

I'm not comfortable getting on a soapbox about race relations in this
country. I want and strive to be an ally but I think my place is to
listen and support not dictate.

Even so, we keep hearing about police accountability on one side that
they need their protections on the other. I thought I'd look at that
and compare the job of a police officer to that of a teacher. 

** My experience

On the one side, I've been a teacher for close to 30 years. On the
police side? I've never been a cop but I was an auxiliary cop for a
while. I stopped soon after I went in to teaching. I was able to do it
while on Wall Street but teaching is just so much harder and more
draining that I didn't have the energy. As an auxiliary cop I got a
bit of an inside view. I didn't patrol the bad parts of the precinct
much - Manhattan Valley,  but I did a bit. I also got to interact with
the police and was listening to police radio during my tours so knew
what was or wasn't going on.

** Key Requirements

*** Police
Sixty college credits or military experience, pass a written and
physical test, psychological test and then the Police Academy.
 
*** Teachers

Masters degree, standardized tests, student teaching although the
quality ranges from rigorous preparation to fly by night TFA nonsense.

** Perceptions
*** Police

On the one side you have police as heroes. This is probably to an
extend residual from 9/11 grouping them in with firefighters and
EMT. You'll also hear that they face death every day and if there
weren't protections like qualified immunity you'd never have anyone
sign up for the job. We also keep hearing that the "majority are good
cops" and "only a few bad apples."

On the other side, ACAB.

*** Teachers

On the one hand you'll hear we're the backbone of society and should
be paid more.

On the other, we're glorified babysitters who do nothing for pay and
pension. 


** Reality 

This post isn't really about teaching so I'm not going to dwell on
that side other than as a comparison but education going remote has,
if nothing else, proven that teachers are anything but lazy
goodfornothings.

On the police side, video evidence shows that a few bad apples do
indeed spoil the bunch and when both police commissioners and polie
union chiefs and even mayors repeatedly lie, distort and omit you know
we need some real changes. I keep hearing about the police needing to
maintain order and acting reasonably but with all those body cameras
plus police officers specifically at protests to film and document I
haven't seen anything backing the police line. 


As to the police facing death every day? Yes, there's always the
possibility of a bad encounter but in my time with the auxiliary I
can't ever remember hearing a call for "officer needs assistance" nor
vary many intense situations. Most of the job was being in the
community. In fact, it turns out that most police officers go through
their entire careers [[https://www.pewresearch.org/fact-tank/2017/02/08/a-closer-look-at-police-officers-who-have-fired-their-weapon-on-duty/][never firing their weapon]]. 

At the same time, teachers in many schools face violence or the threat
of violence and are under no circumstances allowed to even touch a
student. We are supposed to deescalate. Is there a reason why police
can't do the same? 

** On reform

Some people are calling for more training but I'm not one of
them. I've had corprorate, teacher, and city training. It's all CYA
garbage. It doesn't change behavior. Eric Garner was choked
in 2014. Chokeholds were banned by the NYPD in, I think around 1993
and you can bet that was in the "training" officers received. Training
reminds good people how to act. Training helps give you a tool if
you're inclined to use it. Hire a thug and no training is going
to make them an angel. 

I'm more on the defund side but that doesn't just mean cut the
budget. Here are a few things I'd like to see:

- Beat cops - this is something that David Dinkins did with
  Commissioner Brown and they never get credit. They took the cop out
  of the car and put them on the beat. On foot. Make them part of the
  community they're policing. Once they went back into the cars they
  were out of the communities. 
- Better accountability - when the next contract comes around we need
  our politicians to take a *hard* line on accountability. Things like
  community review boards, penalties for turned off cameras,
  transparent records on police misconduct. 
- Make police accountable for bad behavior - while police need due
  process, in the rare times there's any accountability it's usually
  in terms of a payout to the public. This doesn't affect the police
  because it's paid by the taxpayer. Let's change that. The city
  contributes to police pensions. Let's reduce that as needed to pay
  for settlements. If not, how about start with the police salary
  scale and adjust it annually to pay for settlements. Make those
  responsible feel it.

  
The sad thing is that unless the protests continue there might not be
change. I fear that we'll get a few speeches and some surface changes
when we need fundamental change. The solutions aren't hard but we
need people in power who will actually implement them. de Blasio came
to office claiming to be a progressive but he caved to the police
force at the first signs of resistance. We need to put up candidate
who will actually represent the people and make changes and then we
actually have to get out and vote them in.



